FROM busybox as builder

WORKDIR /src

COPY . .

RUN chmod +x replaceCodecImports.sh && ./replaceCodecImports.sh
FROM arm32v7/python:3.7-slim-buster

EXPOSE 80

WORKDIR /app

COPY --from=builder /src/Batch/ ./Batch/
COPY --from=builder /src/Standard/ ./Standard/

COPY --from=builder /src/main.py ./
COPY --from=builder /src/requirements.txt ./

RUN pip install -r requirements.txt

WORKDIR /

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80"]