FROM arm32v7/python:3.7-slim-buster

WORKDIR /app

COPY ./Codec-Report-Standard-Python/srcWatteco/*     ./Codec/Standard
COPY ./Codec-Report-Batch-Python/br_uncompress.py    ./Codec/Batch
COPY ./Codec-Report-Batch-Python/constants.py        ./Codec/Batch
COPY ./requirements.txt .

RUN pip install -r requirements.txt

COPY ./main.py .

EXPOSE 80

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80"]